version: '2.2'

services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tmp:/app/tmp  # Persist temp files if needed
    entrypoint: ["python", "run_all.py"]  # Run once
    network_mode: "host"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/vivek/DE-Project/Advertisement-Response-Analysis/tmp:/app/tmp  # Persist temp files if needed
    network_mode: "host"
    command: >
      /bin/sh -c "while :; do python ld_gform_responses.py; sleep 10; done"  # Runs every 10 seconds

  transformer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tmp:/app/tmp  # Persist temp files if needed
    network_mode: "host"
    command: >
      /bin/sh -c "while :; do python clean_and_transform.py; sleep 30; done"  # Runs every 30 seconds

  frontend:
    build:
      context: /home/vivek/DE-Project/Advertisement-Response-Analysis/Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: /home/vivek/DE-Project/Advertisement-Response-Analysis/Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"